### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by jhonfaiber03** [pinterest/pinterest-python-generated-api-client#31]
I'm getting this error:

Exception when calling AdAccountsApi->ad_account_analytics: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Connection': 'keep-alive', 'Content-Length': '64', 'content-type': 'application/json', 'x-content-type-options': 'nosniff', 'x-envoy-upstream-service-time': '0', 'cache-control': 'no-cache, no-store, must-revalidate', 'age': '0', 'set-cookie': '_ir=0; Max-Age=1800; HttpOnly; Path=/; Secure', 'x-pinterest-rid': '1337919202421304', 'Date': 'Tue, 22 Aug 2023 20:50:58 GMT', 'X-CDN': 'fastly', 'alt-svc': 'h3=":443";ma=600', 'Pinterest-Generated-By': 'tpp-api-canary-0a019891'})
HTTP response body: {"code":2,"message":"Authentication failed.","status":"failure"}

I have created the API and it's already Trial access active, so I generate the token for the sandbox environment, which provides access to all these scopes:
https://developers.pinterest.com/docs/getting-started/scopes/#OpenAPI%20security%20definitions

So, I don't know what's the problem. By the way I have Analyst access to the ads account.

**Comment by dfana01** [comment]
Hi,

Since you've already generated an API token and have active trial access, it might be an issue with how the token is being used within your code. Here's what you can check:

- Token Usage: Are you correctly setting the token in your requests? Can you provide the full code? Example of possible code. 

```python
configuration = openapi_generated.pinterest_client.Configuration(
    host = "https://api.pinterest.com/v5"
)
configuration.access_token = 'YOUR_ACCESS_TOKEN'
```

- Refreshing the token: Sometimes, tokens can expire, become invalidated or corrupted. Try regenerating a new token to resolve this.

**Comment by dfana01** [comment]
Hello @jhonfaiber03 ,

Due to the lack of response, we will temporarily close the issue. 

However, please feel free to reopen it if the issue continues or if there are any new developments or insights that need to be addressed.
